---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/nessmedi/public_html/escuela_sys/
    - /bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='node_modules' --exclude='storage' ./ $DEPLOYPATH